name: Penumbra LCD CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  penumbra-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Build Penumbra LCD
        run: cargo build --release
